### ISSUE TITLE
Is it possible to use environ in the leiningen project file?

### ISSUE THREAD

**Issue by drusellers** [weavejester/environ#25]
I thought that would be a good place to document how to do this. Key use case is that i have a collection of database entries in my profiles.clj and I would like to reuse that data to drive ragtime which is also defined in my project.clj.

**Comment by geofflane** [comment]
:+1:

**Comment by ilmoraunio** [comment]
Clojure hobbyist here. Been struggling with this for days... tried :injections after which I managed to get `environ.core` loaded in repl, but `lein ragtime migrate` doesn't seem to get the namespace loaded. `(env :database-url)` doesn't work either.

What am I doing wrong here (most likely many things)?

Any help or redirection is appreciated.

Stack trace after `lein ragtime migrate`: https://gist.github.com/ilmoraunio/60b3fd2c5f3b6e3ef653
`project.clj`: https://gist.github.com/ilmoraunio/0e2a0c18301ec61886e1#file-project-clj-L62
`profiles.clj` (in case relevant): https://gist.github.com/ilmoraunio/5555a3caa388bc22e740

**Comment by weavejester** [comment]
You might be able to get it working by including Environ as a plugin. However, this is more a Leiningen or Ragtime issue than an Environ issue, so I'm closing this issue.

Also, the next version of Ragtime should have better support for using it with Environ and other in-project configuration systems.

**Comment by TheSeldonPlan** [comment]
Bumping this, did anyone find a solution? I'd like to add my datomic login to the repositories vector, storing the values in my `.lein-env`.

**Comment by drusellers** [comment]
Agreed that the current version (2/5/2016) works much better with environ type tools now. :+1:
