### ISSUE TITLE
Environ when running as an uberjar

### ISSUE THREAD

**Issue by bensu** [weavejester/environ#26]
Should environ work if I compile the project with `lein uberjar` and then run it directly from java:

     java -jar path/to/standalone.jar

or is it only meant to work when running with lein?

**Comment by weavejester** [comment]
It won't pick up the environment from the project file, but it will use the shell environment and system properties.

**Comment by bensu** [comment]
Thanks James.

So if I set `SERVER_PORT=8080` in the shell environment it should then be able to pick it up if I ask for `(env :server-port)` in my code.

**Comment by weavejester** [comment]
Correct.

**Comment by bensu** [comment]
Thanks!

**Comment by tangrammer** [comment]
Firstly, thanks  @weavejester for another good clojure lib!
but, maybe is it a good idea to put this behaviour in the README ? I spent a lot of time asking about why my docker wasn't passing properly env vars to my clojure app 

Regards!

**Comment by jeaye** [comment]
Agreed with above; based on everything I saw, I was expecting environ to put the `:env` bits from my `project.clj` into the uberjar, in some fashion, so it'd be available when I run it. Making this behavior very clear would be helpful.
