### ISSUE TITLE
environ not reloading changes (even after refresh)

### ISSUE THREAD

**Issue by murtaza52** [weavejester/environ#28]
Hi,
I am using environ and develop using emacs and cider. Cider has the C-c C-x for refresh which in turns reloads all the code and namespaces. 

I had changed my profiles.clj, and was expecting that the data in the file would turn up when I did 'refresh' and evaluated the 'env' fn. However I had to restart my repl for the changes to show up. 

What am I doing wrong ? How do I get environ to load changes in the profiles.clj file ?

Thanks,
Murtaza

**Comment by weavejester** [comment]
Environ captures the environment in which the current process is started, which is fixed for the life of the process.

You need to distinguish between your configuration (which can change) and your process environment (which cannot). See issue #16 for a further explanation.
