### ISSUE TITLE
Missing change-log to help users wishing to upgrade

### ISSUE THREAD

**Issue by sdegutis** [weavejester/environ#31]

**Comment by weavejester** [comment]
There's no significant changes to put in a change log. Environ is only version 1.0, and the API hasn't changed since the first unstable release.

**Comment by sdegutis** [comment]
Right, I figured that out by scanning through the commits. But even putting what you said in the readme could save others looking to upgrade the 10 minutes I spent. Anyway, your call.

**Comment by weavejester** [comment]
Well, no-one else has complained, and it's only had one stable version released, so I don't think any additional notes are necessary. But if I get a lot of people asking, maybe I'll add in a note to that effect.
