### ISSUE TITLE
Needs to be updated on clojars

### ISSUE THREAD

**Issue by bsima** [weavejester/environ#35]
boot-environ has not yet been pushed to Clojars, and it looks like there are some commits to environ.core that are not yet in Clojars. Is there anything preventing this from being updated? Is there anything I can do to help out? Right now I literally copied the environ.boot namespace and code into my src directory so I could use it

**Comment by weavejester** [comment]
I haven't had time to properly review boot-environ and release it yet. I'll try and make some time for it today.

**Comment by weavejester** [comment]
I've released boot-environ 0.1.0-SNAPSHOT as a temporary measure.

**Comment by weavejester** [comment]
I fixed a bug in the implementation, and I've released boot-environ 1.0.0-RC1.
