### ISSUE TITLE
Always cast value to string?

### ISSUE THREAD

**Issue by visibletrap** [weavejester/environ#36]
This could be only my own stupidity. It took quite a bit of time for me to debug my application and found out that the cause of the bug is values retrieving from environment variables are always be in string type. My application is working fine in local machine because I was testing it in against a number value as profiles.clj (edn) differentiates number from string (which it's designed to be).

I would propose environ to convert all number values which are set in profiles.clj to be string as environment variables and Java system properties are only returns string value.

If you think it makes sense to do this, I could come up with a patch.

**Comment by weavejester** [comment]
I've been considering this, but hadn't got around to making a firm decision until now. I think that converting to a string is a reasonable approach, but the library needs to print a warning message when it happens, both to inform the user what's happening, and to encourage them to use strings in their Leiningen configuration.

**Comment by visibletrap** [comment]
I think that's a good idea

**Comment by visibletrap** [comment]
Sorry for no update on this. I'm in the process of moving country so I probably won't get to do this at least for a week ahead.

I'm afraid that I'm living a stale issue here. Is it ok? I'm also fine if we are just going to close this for now and I'll reopen it when I got the patch.

By the way, if anyone want to do this, please go ahead implementing it.

**Comment by visibletrap** [comment]
I implemented [this in lein-environ plugin](https://github.com/visibletrap/environ/commit/51bef10c3afa0d696580ec9d060ed92a125b94eb). Do you think it's ok or do you prefer it to be implemented in environ.core?

**Comment by weavejester** [comment]
Apologies for the late response. The notification got lost in my inbox.

I think the right place for this is environ.core. The `sanitize` function should be renamed `sanitize-key` and a new `santize-val` function should be added.

**Comment by weavejester** [comment]
Fixed by #45.
