### ISSUE TITLE
ClojureScript use?

### ISSUE THREAD

**Issue by orlin** [weavejester/environ#40]
I'm trying to write code that works for both clojure and clojurescript, where applicable.  Using env vars is something I'd like to do on both sides.  Do you have plans to add clojurescript support, or else could you point me to an alternative?  Perhaps there is some way to pass certain vars on through leiningen (figwheel / devcards) or boot to a frontend app?  Planck is another context I'd like to run stuff with from the cli...

**Comment by weavejester** [comment]
ClojureScript support for node.js you mean? Or for a browser?

**Comment by orlin** [comment]
Just [lein figwheel #devcards](https://github.com/bhauman/devcards) to begin with, and web apps (via boot-clj) somewhat later.

I also run some of the code from a shell / `planck`, mostly because my hardware isn't quite strong-enough to use jvm for that yet.  So I've got a workaround idea for setting up the env for planck cli use.  I like @davidnolen's [opinion in this discussion](https://gist.github.com/mfikes/c7da1e7dfded26c7ceb9#gistcomment-1546981) concerning node, though for "generality" I may just end up having a node.js cli to install through npm, as there doesn't seem to be a worked-out node.cljs yet.  As far as using node + clojurescript server-side -- that would be interesting...  For example there are currently [a couple of pull requests](https://github.com/ptaoussanis/sente/pulls) for having the sente server run on cljs / node.

**Comment by weavejester** [comment]
The notification for this response seems to have gotten lost in my inbox, so apologies for the late reply.

ClojureScript executed in a browser doesn't have access to environment variables of system properties, so I'm not sure what you're suggesting.

**Comment by orlin** [comment]
Let's say I borrow code from [alda](https://github.com/alda-lang/alda) which is all-Clojure -- I liked the way it does `build.boot` tasks (they are getting even better with the 1.0 version), and also want to run some cljs dsl commands from a [planck](https://github.com/mfikes/planck) cli, just for getting faster response times.  This is my starting context in another domain, though node.js may be a consideration (your first question) / could be cropping-up more often in general, like this [conj talk](https://www.youtube.com/watch?v=fICC26GGBpg) at 16:40 mentions node briefly as being undesirable in production.  A further goal is to build a web app / electron app, starting with devcards, which would use the same codebase.  I'm somewhat detached from the details right now, working on other things temporarily...

**Comment by weavejester** [comment]
I'm still not completely sure what you're suggesting. If ClojureScript is running in the browser, it has no environment to speak of (unless you're counting local storage, cookies, etc.)

**Comment by sickill** [comment]
@orlin maybe the following will help you.

I have created a macro that I use in my ClojureScript source file. Because ClojureScript macros are writtent in `.clj` files (they're Clojure code) they have access to all things Clojure/Java/OS and thus to Environ.

Here's how I did it: https://github.com/asciinema/asciinema-player/commit/facc64737155765200f8dcba5dc2a0fe58e65fc7

This only makes sense if you always compile before running, as it captures (and hardcodes in resulting `.js` file) the env the compilation happened in.

**Comment by ZabelTech** [comment]
@weavejester  
do you take a pull request for this?

It makes senses for a lot of cases where you want to define compile time variables.
think of having a testing and a production build with different server uris, or wrapping the print-function so that it only prints in non-production environments, also with a third-party sdk like  e.g. paypal or FB you could use sandbox and production environments, depending on the profile.

All it really takes is a macro that passes the environ.core/env in compile time and a def in a cljsnamespace with the same name.

what do you think?

**Comment by sickill** [comment]
@ZabelTech that would be super nice!

**Comment by weavejester** [comment]
I can see how that's useful, but don't think it should be built into Environ. It's beyond the scope of what Environ aims to do, and seems like a fairly niche requirement.

**Comment by ZabelTech** [comment]
wow that's fast :)

i really appreciate your work, but what is the scope then?
In your readme you give the example of having three different database connections for testing, etc.

it's basically the same thing from clojurscript, thinking of versioned apis with different endpoints, thinking of integration tests against the whole stack on a different endpoint and, what i said, against sandbox environments you need to define in clojurescript 
.
What i  just did was using pallet/lein-sha-version to pull in the git sha hash passing it to the env map to set a cookies with that value from clojurescript for a cordova app, to know server-side what version i'm dealing with. 
that way there is no manual labor involved.

Could I do this all by hand for every build? Yes, also i can write my own macro. 

I just think it's way more handy to just require environ.core/env from clojurescript and use it as I'm used to.

Also there is no change in your code necessary, only additions. I don't see where the harm could be.

**Comment by weavejester** [comment]
Environ's purpose to provide access to the environment of the running process. Providing access to the environment that the code was compiled in is somewhat different.

Also, you seem to be suggesting that in Clojure, the `env` var contains the environment of the running process, but in ClojureScript the `env` var contains the environment of the *compiling* process. That's two separate uses for the same var, which seems like a bad idea.

**Comment by ZabelTech** [comment]
allright, in that perspective i can see the separation.
but from the use case perspective, assuming you don't do (assoc env :browser :chromium, or anything in the profiles.cljs), the environment of the running process, is the same as the environment of the compiling process (production,testing, etc.), as long as you won't change the env in the running process, but that holds true for clojure as well.

**Comment by ZabelTech** [comment]
ok forget the last sentence, it doesn't hold true. just saying that it's handy to define values on compile time that are accessible on run time in clojusersctipt.
to me that's what you do with environ in clojure, except it's not only compile time there but also run time, but i think hooking in with a nrepl and changing the env is rather niche.

**Comment by weavejester** [comment]
Why not create another library for doing this?

**Comment by ZabelTech** [comment]
allright, you mind if i name it cljs-environ? because people (in my mind, technicalities aside) now what to except. and i just wrap environ (like i described above), because i think it does everythink necessary really well.

**Comment by ZabelTech** [comment]
except=expect

**Comment by weavejester** [comment]
I'd prefer it if it was named something slightly less ambiguous. ClojureScript can compile to Node, after all, which *does* have access to the process environment.

**Comment by ZabelTech** [comment]
that's intersting, i have to check that out :)
allright good night then

**Comment by raymcdermott** [comment]
I know this is closed but - for the sake of future visitors -  I would like to add a reference to the CLJS IJavaScriptEnv protocol which provides support for this https://clojurescript.org/reference/repl

**Comment by orlin** [comment]
I just spotted [env-config](https://github.com/binaryage/env-config) that does this, though only via environment variables.

**Comment by johanatan** [comment]
`goog.define` & `:closure-defines` seems the most idiomatic approach to this (IMHO).
