### ISSUE TITLE
Where the production configuration should be stored?

### ISSUE THREAD

**Issue by avli** [weavejester/environ#42]
According to the environ documentation `dev` environment is used when one runs repl, `test` environment is used for `lein test`. But what is the proper way for defining production environment with environ? Should I define `prod` profile and use it when building uberjar before deploying application to the server? Or should I consider to use environment variables or Java properties instead? Thank you!

**Comment by weavejester** [comment]
Sorry about the late response. Environment variables or (less commonly) Java properties.

**Comment by avli** [comment]
@weavejester No worries, thank you for the answer! Probably, it worth mention this in the documentation.

**Comment by neverfox** [comment]
@avli Yeah, the idea is that there is no such thing as a production profile, in that when you're talking production, you should be fully in 12-factor mode, which is to say, all environment variables. Environ's ability to use local files is to take advantage of profiles that exist when using lein or boot which, by definition, are sub-production tools. From the code's perspective, it's all coming from the environment, but it's often just more convenient during dev and test to bootstrap that environment using the same tool that bootstraps everything else. It's up to you how those environment variables ultimately get populated in production.
