### ISSUE TITLE
Warn when environment defaults are not strings

### ISSUE THREAD

**Issue by DanBurton** [weavejester/environ#43]
It seems fishy to me that one can set

   `:env {:port 5000}`

And that this is loaded as the number `5000`, but if one's environment variables override this with (for example) `PORT=5001 lein run`, then `:port` will be set to the string `"5001"`. This can lead to subtle bugs.

It makes more sense to me to only allow string values in the environment map. Or at least, to log a warning when non-string environment default values are loaded.

**Comment by weavejester** [comment]
This issue is already covered by #36.
