### ISSUE TITLE
boot-environ does not update environment in pods

### ISSUE THREAD

**Issue by loomis** [weavejester/environ#46]
The current `boot-environ` task updates the internal var containing the environment and passes this on to subsequent tasks.  However, this does not work for tasks that create their own pods (such as the `boot-test` task) because modified objects are not passed into pods when they are initialized.  This makes testing code which uses `environ` for configuration difficult (or at least non-intuitive). If the task were to manage a `.lein-env` file in the fileset in parallel with changes to the var, then the task should work identically for all tasks and make the task more useful.

I have a modified task which does this and can make a pull request if you agree with the suggested change.

**Comment by weavejester** [comment]
Make it a `.boot-env` file, and we can change the core library to check for `.lein-env` or `.boot-env`. But yes, this sounds like a good idea.

**Comment by loomis** [comment]
Ok, I'll put together a pull request.

**Comment by loomis** [comment]
I've responded to all of the comments on the PR and tested the code again.  Please take another look and see if there's anything else amiss.
