### ISSUE TITLE
Environ does not correctly find some Windows environment variables

### ISSUE THREAD

**Issue by kennycoc** [weavejester/environ#51]
I have set a variable DATABASE_URL.

Calling `echo %DATABASE_URL%` correctly outputs the correct url, but calling `(env :DATABASE_URL)` returns nil.

**Comment by kennycoc** [comment]
I just saw that environ converts to lowercase. Because windows is case-insensitive, I do not believe this is the problem. 
Checking environment variables set via the command line, it does return the correct value.

Possibly, it does not thoroughly check windows environment variables, so that ones set via the control panel do not get found

**Comment by weavejester** [comment]
Have you tried `(env :database-url)`? As the README notes:

> Note that Environ automatically lowercases keys, and replaces the characters "_" and "." with "-". The environment variable `DATABASE_URL` and the system property `database.url` are therefore both converted to the same keyword `:database-url`.

**Comment by kennycoc** [comment]
Yes, I tried changing the actual environment variable to lowercase too. `(System/getenv DATABASE_URL)` picks it up correctly too..

**Comment by weavejester** [comment]
Did you also change the `_` to a `-`?

**Comment by kennycoc** [comment]
Oh! Yeah, that's probably the problem. Anyways, it looks like it won't work
for my uses, as heroku stores the variable in all caps with an underscore.
May I ask why the decision was made to convert the identifiers?

**Comment by weavejester** [comment]
System properties, project keywords, and environment variables all use different naming schemes. Environ converts them all to the same format. Environ works fine under Heroku, because even though Heroku stores the variable in all caps with an underscore, Environ converts it into the more idiomatic standard of lowercase + dashes.

**Comment by kennycoc** [comment]
Hm.. So, I can use (env :database-url), and it will find DATABASE_URL?

**Comment by weavejester** [comment]
Right. As the README says:

> Note that Environ automatically lowercases keys, and replaces the characters "_" and "." with "-". The environment variable `DATABASE_URL` and the system property `database.url` are therefore both converted to the same keyword `:database-url`.

**Comment by kennycoc** [comment]
Sorry, I guess I misread. Thanks!
