### ISSUE TITLE
Feature request: Support Boolean variables

### ISSUE THREAD

**Issue by rationalism** [weavejester/environ#58]
For a map key/value pair in the profiles file like ":dev-environment false", it looks like environ will issue this warning:

"Warning: environ value false for key :in-dev has been cast to string"

and then turn the value false into the string "false", which of course evaluates to true. Could environ be extended to support Boolean map keys like this? Thanks.

**Comment by weavejester** [comment]
Environment variables and system properties can only be strings. While the project file can use other data structures, Environ supports the lowest common denominator. This allows the same code to be used in development (with the project file), and in production (with environment variables or system properties).
