### ISSUE TITLE
sanitize function strips keyword namespace

### ISSUE THREAD

**Issue by ikarius** [weavejester/environ#67]
Hence something like
`{:slack/send-url "http:/...:"}`
in .lein-env leads to:
`Warning: environ key :slack/send-url has been corrected to :send-url`

**Comment by thedavidmeister** [comment]
i just ran into this.

can't use namespaced keywords for environment variables :( :( :(

**Comment by weavejester** [comment]
Environ draws in keys from the project configuration, the system properties, and environment variables. To make everything consistent, it needs to cater to the lowest common denominator. As system properties and environment variables do not have namespaces, we can't have namespaces in keywords, either.
