### ISSUE TITLE
Why cast to string?

### ISSUE THREAD

**Issue by itaied246** [weavejester/environ#74]
Why does `environ` cast values to strings?
I am passing the port (which is a number) as a number,
but `environ` casts it to `string`.

Can disable this behavior?

**Comment by weavejester** [comment]
Environment variables and system properties are always strings, so Environ
has to cater for the lowest common denominator.

**Comment by itaied246** [comment]
Ok thanks.
Do you have any suggestion how to handle casting and validations?
For example, bootstrapping the app from the env vars.

**Comment by weavejester** [comment]
I'm afraid that's beyond the scope of the library. Environ only provides a
way of accessing the environment in a Clojure-friendly way. It isn't a
library that handles configuration or coercion.

**Comment by itaied246** [comment]
Yes of course, I understand that and I agree it's beyond the scope of this library.
I was asking as a beginner of clojure, from other projects you know or practices you came across, is there any best practice to manage the configuration and bootstrapping?

**Comment by weavejester** [comment]
You might want to take a look at [Aero](https://github.com/juxt/aero) for pure configuration, or [Duct](https://github.com/duct-framework/duct) if you want a more complete framework (I have an incomplete [guide](https://github.com/duct-framework/docs/blob/master/GUIDE.rst) to starting in it). There's also [Nomad](https://github.com/jarohen/nomad), and you can always load in a configuration manually, too.

**Comment by itaied246** [comment]
Ok thanks I'll take a look at that.
