### ISSUE TITLE
update clojure version to 1.9.0

### ISSUE THREAD

**Issue by mikeThurmond** [weavejester/environ#86]

**Comment by weavejester** [comment]
What's your reason for updating the minimum Clojure version?

**Comment by mikeThurmond** [comment]
I wasn't sure by updating from java 8 to java 11 if the dependency would still work.  My apologies if I am incorrect.  I was having trouble compiling my program, but it looks like an issue with ring.  I can close this if want.

Thanks

**Comment by weavejester** [comment]
The Clojure dependency is the minimum version of Clojure this library supports. This issue essentially says "You should only support the latest Clojure version", which I don't think is what you were intending.

**Comment by mikeThurmond** [comment]
Gotcha, thanks for explaining and being patient.  Closing issue now.
