### ISSUE TITLE
<project>-version key is nil in uberjar

### ISSUE THREAD

**Issue by Freezystem** [weavejester/environ#90]
Hi ! 
I'm currently using `(env :<project>-version)` in my project and it's working fine when running project from `lein repl`.  

But, as soon as I build my jar with `lein uberjar`, the `:<project>-version` key seems to be `nil`.  

I'm a doing it wrong or is there some known workaround ?

Regards,

**Comment by weavejester** [comment]
It's in the README, but a little far down:

> *Important* -- environ will not pick up configuration settings from the project.clj when called from a compiled uberjar. So for any compiled code you produce with lein uberjar, you will want to set your configuration values via shell environment and/or system properties.

**Comment by Freezystem** [comment]
Thanks a lot. Sorry for asking already documented question.
Regards,
